<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AppUsageMonitor.Reports</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AppUsageMonitor.Database\AppUsageMonitor.Database.csproj" />
  </ItemGroup>

</Project>
